### PR TITLE
contribution

### PR DESCRIPTION
**Pull request by chaos-ui**

### CODE REVIEW

**Comment by chaos-ui** [comment]
please tag as help needed as I am not seeing it to add right now.

**Comment by mikebudzynski** [comment]
@chaos-ui, could you provide more details on this PR?

**Comment by chaos-ui** [comment]
Hello, the PR is in line with 
.github/workflows/master_engix.yml

name: Azure App Service - EngiX(Production), Build and deploy DotnetCore app

Contribution was made by me from azure portal

**Comment by mikebudzynski** [comment]
1. Can you explain the reason behind removing the files, like the community contributed widget, images, and fonts?
2. What do the contributed workflows do and how can they be used by the other community members?

**Comment by chaos-ui** [comment]
Hello this is an Azure resource from Azure app services, developed via Azure portal. I am rather new to this community and I'm glad for your help. This was intended to contribute for everyone to use however I did not realize it would erase the main files I thought I had made a separate contribution. do you all think I should close this? Next time I will make sure to give a better explanation or at least submit the links and references in a clearer manner thank you.

**Comment by mikebudzynski** [comment]
@chaos-ui, thanks for your contribution, but we can't merge this pull request due to the following reasons:

1. It removes other files from the repository
2. It references secrets specific to your profile only
3. It lacks clear explanation of the contributed functionality and instructions

**Comment by chaos-ui** [comment]
Thankyou Mike I whole heartedly appreciate you explaining of this!

**Pull request closed without merging**
