### PR TITLE
Added files for backing up and restoring the portal

### LINKED ISSUE #848: Scripts for easily backing up and restoring the portal
## Bug description

When customizing the portal it is impossible to undo a change once you have saved it. That makes it risky to work with it. There are two scripts that exist that let you save the customizations; migrate.js and capture.bat. However, capture.bat does not save the media files and migrate.js uses hard coded paths and requires information about a destination portal. Therefore it would be great if there was a script for easily backing up the customizations, preferably with an option to add a timestamp to the file name and the folder name.

If you are able to specify the paths you would be able to put the files directly in a folder where it may be connected to a repository.

Also, an accompanying script for restoring/bringing up a portal using the saved files would be great. That would enable it to work with continuous delivery.

### PR DESCRIPTION
**Pull request by ErikMogensen**
This would fix #848 

Most of the code is copied from migrate.js. To remove the duplicated code, migrate.js could use the functions in shared.js.

### CODE REVIEW

**Comment by shashiguru** [comment]
Hi there, i have reviewed the code of 3 files but as we already have .bat files for generate, capture. we can use those to do backup and restore. do we really need these files now?

**Comment by ErikMogensen** [comment]
Hi,

Since capture.bat does not save the media files my initial plan was to just create a bat file that called capture.bat and then did the az storage ... command but I changed my mind and made a Javascript wrapping those calls for the following reasons:

- Need to create the folder for the media files
- Handling the complex parameters, yargs does an excellent job of doing that
- Ability to save often without overwriting the previous save

**Comment by ErikMogensen** [comment]
Another way of solving the main issue would be to add the possibility to save media files to capture.bat and capture.js and the upload functionality to the generate.* files.

 It would be great if the ability to save often without overwriting the previous save was added to the capture.* files too.

**Comment by azaslonov** [comment]
Hi folks, just wanted to update you. We need to land an important change around API and related scripts before merging this PR. When done, we'll give specific pointers of what needs to be changed (if anything). Thanks for your contribution.

**Comment by azaslonov** [comment]
Hi @Erik, thanks for your contribution, we greatly appreciate your help!

However, I think @shashiguru is right - there are files doing similar things. I was thinking to re-work capture/generate JS files into what you have in backup/restore JS files and just change the invocation of those files in capture/generate BAT files. This way we could probably solve both concerns. Also, I think naming "backup" and "restore" is more appropriate as well.

Therefore, maybe if you have spare time and willing to re-work these scripts a bit, we'd be even more grateful. If not, we'll do it in the next couple of weeks.

**Comment by ErikMogensen** [comment]
Hi Alex,

I agree changing the capture/generate JS files is better. It requires more work though since you would have to change depending scripts, but I see that you already have done these changes to the scripts in scripts.v2 :smiley:. I also see that you got rid of the dependency to Azure CLI, which is great 👍 

As far as I can tell there are some features that are not there; the ability to publish when running generate.js and the ability to add a timestamp when saving. I also liked the functionality of yargs for the parameter handling.

I will happily add those features, but do you want them?

**Comment by azaslonov** [comment]
> Hi Alex,
> 
> I agree changing the capture/generate JS files is better. It requires more work though since you would have to change depending scripts, but I see that you already have done these changes to the scripts in scripts.v2 😃. I also see that you got rid of the dependency to Azure CLI, which is great 👍
> 
> As far as I can tell there are some features that are not there; the ability to publish when running generate.js and the ability to add a timestamp when saving. I also liked the functionality of yargs for the parameter handling.
> 
> I will happily add those features, but do you want them?

Hi Erik, sorry for the late response. Yes, actually if we could have those (timestamp and publishing flag) as parameters, I think it would be awesome.

**Comment by ErikMogensen** [comment]
No problem. Glad to see that you want those features. I'll add them during the next month.

**Comment by jake-scott** [comment]
Hi.. I actually ported the JS files to a Golang CLI that can be used to backup/restore/reset the portal :+1: 

  https://github.com/jake-scott/apim-tools

The JS tools were a useful reference, but they are not production ready, and require the user present a SAS token.  The tools above obtain the SAS token from the Azure RM API, and authenticate the caller using standard Azure AAD.

I hope that is useful!

**Comment by azaslonov** [comment]
Closing PR, since the mentioned logic was implemented in #1031.

@jake-scott, to my shame I noticed your comment just now, your work probably would have saved me a lot of time. I see your solution also based on ARM and `az login` approach, plus that you've done some nice reporting and more. I hope you don't mind us stealing some things :)

**Pull request closed without merging**
